# Site settings
title: Gav's Site
email: kerr5140@mylaurier.ca
description: > # this means to ignore newlines until "baseurl:"
  A simple guy with a simple site about something he loves while
  simultaneously learning a thing or two about web design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: GavinKerr14
github_username:  Gav1442

# Build settings
markdown: kramdown
